spring.datasource.url=jdbc:postgresql://dpg-d6mqjok50q8c73aotih0-a:5432/taskmaster_db_1v8c?user=taskmaster_db_1v8c_user&password=OSJ1LEyp7XnbE8IvDyuAk2U9BYplkX0h
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}