spring.datasource.url=jdbc:postgresql://dpg-d6n75fdactks738gaqfg-a:5432/taskmaster_db_vx6v?user=taskmaster_db_vx6v_user&password=h4C71dUgwXGSq8QqvPKvR47lIxV5Gojl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}